### ISSUE TITLE
start 报错

### ISSUE THREAD

**Issue by KkEeVvIiNnn** [HomeArchbishop/majsoul-analyser#1]
\> yarn start
yarn run v1.22.19
$ npx ts-node server/index.ts
Error: Cannot find module './build/Release/robotjs.node'
Require stack:
\- C:\Users\Kevin\Desktop\majsoul-analyser\node_modules\robotjs\index.js
\- C:\Users\Kevin\Desktop\majsoul-analyser\server\bot\robotjs\index.ts
\- C:\Users\Kevin\Desktop\majsoul-analyser\server\bot\index.ts
\- C:\Users\Kevin\Desktop\majsoul-analyser\server\index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\Kevin\Desktop\majsoul-analyser\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Kevin\Desktop\majsoul-analyser\node_modules\robotjs\index.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\Kevin\Desktop\majsoul-analyser\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Kevin\\Desktop\\majsoul-analyser\\node_modules\\robotjs\\index.js',
    'C:\\Users\\Kevin\\Desktop\\majsoul-analyser\\server\\bot\\robotjs\\index.ts',
    'C:\\Users\\Kevin\\Desktop\\majsoul-analyser\\server\\bot\\index.ts',
    'C:\\Users\\Kevin\\Desktop\\majsoul-analyser\\server\\index.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by KkEeVvIiNnn** [comment]
非常感谢！成功了！
